container:
  image: python:3.5

test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt && pip install flake8
  check_script: flake8
  test_script: pytest